<?php

/********************************
 * DO NOT ADD ANYTHING TO THIS FILE.
 * THIS FILE IS AUTO GENERATED BY "Workhorse" PACKAGE.
 *******************************/


/**
 * Plugin Name:  Workhorse Plugin
 * Description:  Workhorse Plugin.
 * Version:      1.0.0
 * Author:       Anbit Digital Engineering
 * Author URI:   https://anbit.io/
 * License:      MIT License
 */
